# Generated by Django 3.1.3 on 2020-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='roll',
            field=models.CharField(default='-1', max_length=200, unique=True),
        ),
    ]
