# Generated by Django 3.1.3 on 2020-11-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201119_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='section_number',
            field=models.CharField(default='-1', max_length=200, unique=True),
        ),
    ]
