# Generated by Django 3.1.3 on 2020-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201121_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='available_seat',
            field=models.IntegerField(default=0),
        ),
    ]
