# Generated by Django 3.1.5 on 2021-01-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sectionmodel_booked_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='fk_teacher',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.teachermodel'),
        ),
    ]
